name: CI
on:
  push:
    branches:
    - "main"
    - "feat/forgejo-pipelines"
    tags:
    - 'v[0-9]*.[0-9]*.[0-9]*'
  pull_request:
    branches:
    - "main"
    - "release/*"

jobs:
  format-check:
    runs-on: tox-alpine-pod
    steps:
    - run: |
        sudo apk add --no-cache \
          meson \
          muon \
          clang21-extra-tools \
        && :
    - uses: actions/checkout@v4
    - name: muon fmt
      run: |
        if ! find . \( -name meson.build -or -name meson_options.txt \) -print0 \
            | xargs -0 muon fmt -q; then
          find . \( -name meson.build -or -name meson_options.txt \) -print0 \
            | xargs -0 muon fmt -i;
          git diff
          exit 1
        fi
    - run: |
        meson setup build
    - name: clang-format
      run: |
        ninja -C build clang-format-check

  test-debian:
    needs:
    - format-check
    runs-on: tox-debian-vm
    steps:
    - run: |
        sudo apt update
        sudo apt install -y --no-install-recommends \
          meson \
          squashfs-tools \
          bsdextrautils \
          build-essential \
          libcurl4-openssl-dev \
          libfuse-dev \
          libfuse3-dev \
          liblz4-dev \
          liblzma-dev \
          zlib1g-dev \
          libzstd-dev \
        && :
    - uses: actions/checkout@v4
    - name: configure
      run: |
        CC=gcc meson setup build \
          -Dwerror=false \
          -Dexamples=true \
          -Dcurl=enabled \
          -Dzlib=enabled \
          -Dlz4=enabled \
          -Dlzma=enabled \
          -Dzstd=enabled \
          -Dthreads=enabled \
          -Dfuse-old=disabled \
          -Dtest=extended \
          -Ddoc=false \
        && :
    - name: build
      run: ninja -C build all
    - name: test
      run: ninja -C build test

  test-alpine:
    needs:
    - format-check
    runs-on: tox-alpine-pod
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
    - run: |
        sudo apk add --no-cache \
          meson \
          hexdump \
          squashfs-tools \
          build-base \
          curl-dev \
          fuse-dev \
          lz4-dev \
          xz-dev \
          zlib-dev \
          zstd-dev \
          gcc \
          clang \
        && :
    - uses: actions/checkout@v4
    - name: configure
      run: |
        CC=${{ matrix.cc }} meson setup build \
          -Dwerror=true \
          -Dexamples=true \
          -Dcurl=enabled \
          -Dzlib=enabled \
          -Dlz4=enabled \
          -Dlzma=enabled \
          -Dzstd=enabled \
          -Dthreads=enabled \
          -Dfuse-old=enabled \
          -Dtest=true \
          -Ddoc=false \
        && :
    - name: build
      run: ninja -C build all
    - name: test
      run: ninja -C build test

  test-openbsd:
    needs:
    - format-check
    runs-on: tox-openbsd-vm
    steps:
    - run: |
        sudo pkg_add \
          meson \
          squashfs-tools \
          curl \
          lz4 \
          xz \
          zstd \
        && :
    - uses: actions/checkout@v4
    - name: configure
      run: |
        CC=clang meson setup build \
          -Dwerror=true \
          -Dexamples=true \
          -Dcurl=enabled \
          -Dzlib=enabled \
          -Dlz4=enabled \
          -Dlzma=enabled \
          -Dzstd=enabled \
          -Dfuse-old=enabled \
          -Dfuse=disabled \
          -Dtest=extended \
          -Ddoc=false \
        && :
    - name: build
      run: ninja -C build all
    - name: test
      # fuse needs root privileges on OpenBSD
      run: sudo ninja -C build test
