name: CI
on:
  push:
    branches:
    - "main"
    tags:
    - 'v[0-9]*.[0-9]*.[0-9]*'
  pull_request:
    branches:
    - "main"
    - "release/*"

jobs:
  format-check:
    runs-on: tox-alpine-pod
    steps:
    - run: |
        sudo apk add --no-cache \
          meson \
          muon \
          clang21-extra-tools \
        && :
    - uses: actions/checkout@v4
    - name: muon fmt
      run: |
        if ! find . \( -name meson.build -or -name meson_options.txt \) -print0 \
            | xargs -0 muon fmt -q; then
          find . \( -name meson.build -or -name meson_options.txt \) -print0 \
            | xargs -0 muon fmt -i;
          git diff
          exit 1
        fi
    - run: |
        meson setup build
    - name: clang-format
      run: |
        ninja -C build clang-format-check

  test-debian:
    needs:
    - format-check
    runs-on: tox-debian-vm
    steps:
    - run: |
        sudo apt update
        sudo apt install -y --no-install-recommends \
          meson \
          squashfs-tools \
          bsdextrautils \
          build-essential \
          libcurl4-openssl-dev \
          libfuse-dev \
          libfuse3-dev \
          liblz4-dev \
          liblzma-dev \
          zlib1g-dev \
          libzstd-dev \
        && :
    - uses: actions/checkout@v4
    - name: configure
      run: |
        CC=gcc meson setup build \
          -Dwerror=false \
          -Dexamples=true \
          -Dcurl=enabled \
          -Dzlib=enabled \
          -Dlz4=enabled \
          -Dlzma=enabled \
          -Dzstd=enabled \
          -Dthreads=enabled \
          -Dfuse-old=disabled \
          -Dtest=extended \
          -Ddoc=false \
        && :
    - name: build
      run: ninja -C build all
    - name: test
      run: ninja -C build test

  test-alpine:
    needs:
    - format-check
    runs-on: tox-alpine-pod
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
    - run: |
        sudo apk add --no-cache \
          meson \
          hexdump \
          squashfs-tools \
          build-base \
          curl-dev \
          fuse-dev \
          lz4-dev \
          xz-dev \
          zlib-dev \
          zstd-dev \
          gcc \
          clang \
        && :
    - uses: actions/checkout@v4
    - name: configure
      run: |
        CC=${{ matrix.cc }} meson setup build \
          -Dwerror=true \
          -Dexamples=true \
          -Dcurl=enabled \
          -Dzlib=enabled \
          -Dlz4=enabled \
          -Dlzma=enabled \
          -Dzstd=enabled \
          -Dthreads=enabled \
          -Dfuse-old=enabled \
          -Dtest=true \
          -Ddoc=false \
        && :
    - name: build
      run: ninja -C build all
    - name: test
      run: ninja -C build test

  build-debian32:
    needs:
    - format-check
    runs-on: tox-debian-vm
    steps:
    - run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y --no-install-recommends \
          meson \
          pkg-config \
          build-essential \
          gcc-multilib \
          g++-multilib \
          squashfs-tools \
          bsdextrautils \
          libcurl4-openssl-dev:i386 \
          liblz4-dev:i386 \
          liblzma-dev:i386 \
          zlib1g-dev:i386 \
          libzstd-dev:i386 \
        && :
    - uses: actions/checkout@v4
    - name: configure
      env:
        CROSS_FILE: |
          [binaries]
          c = 'gcc'
          cpp = 'g++'
          ar = 'gcc-ar'
          strip = 'strip'
          pkg-config = 'pkg-config'

          [built-in options]
          c_args = ['-m32']
          c_link_args = ['-m32']
          cpp_args = ['-m32']
          cpp_link_args = ['-m32']

          [properties]
          pkg_config_libdir = '/usr/lib/i386-linux-gnu/pkgconfig:/usr/share/pkgconfig'

          [host_machine]
          system = 'linux'
          cpu_family = 'x86'
          cpu = 'i686'
          endian = 'little'
      run: |
        echo "$CROSS_FILE" > cross-file.txt
        meson setup --cross-file cross-file.txt build \
          -Dwerror=true \
          -Dexamples=true \
          -Dcurl=enabled \
          -Dzlib=enabled \
          -Dlz4=enabled \
          -Dlzma=enabled \
          -Dzstd=enabled \
          -Dfuse=disabled \
          -Dfuse-old=disabled \
          -Dtest=true \
          -Ddoc=false \
        && :
    - name: build
      run: ninja -C build all
    - name: test
      run: ninja -C build test

  test-openbsd:
    needs:
    - format-check
    runs-on: tox-openbsd-vm
    steps:
    - run: |
        sudo pkg_add \
          meson \
          squashfs-tools \
          curl \
          lz4 \
          xz \
          zstd \
        && :
    - uses: actions/checkout@v4
    - name: configure
      run: |
        CC=clang meson setup build \
          -Dwerror=true \
          -Dexamples=true \
          -Dcurl=enabled \
          -Dzlib=enabled \
          -Dlz4=enabled \
          -Dlzma=enabled \
          -Dzstd=enabled \
          -Dfuse-old=enabled \
          -Dfuse=disabled \
          -Dtest=extended \
          -Ddoc=false \
        && :
    - name: build
      run: ninja -C build all
    - name: test
      # fuse needs root privileges on OpenBSD
      run: sudo ninja -C build test

  test-freebsd:
    needs:
    - format-check
    runs-on: tox-freebsd-vm
    steps:
    - run: |
        sudo pkg install -y \
          pkgconf \
          fusefs-libs \
          lzo2 \
          liblz4 \
          zstd \
          meson \
          git \
          squashfs-tools \
          coreutils \
        && :
    - run: |
        sudo kldload fusefs
        sudo sysctl vfs.usermount=1
    - uses: actions/checkout@v4
    - name: configure
      run: |
        CC=clang meson setup build \
          -Dwerror=true \
          -Dexamples=true \
          -Dcurl=enabled \
          -Dzlib=enabled \
          -Dlz4=enabled \
          -Dlzma=enabled \
          -Dzstd=enabled \
          -Dfuse-old=enabled \
          -Dfuse=disabled \
          -Dtest=extended \
          -Ddoc=false \
        && :
    - name: build
      run: ninja -C build all
    - name: test
      # fuse needs root privileges on OpenBSD
      run: sudo ninja -C build test
