name: CI
on:
  push:
    branches:
    - "main"
    tags:
    - 'v[0-9]*.[0-9]*.[0-9]*'
  pull_request:
    branches:
    - "main"
    - "release/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-linux32:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install --yes build-essential gcc-multilib g++-multilib python3-pip python3-venv
        python -m pip install --upgrade pip
        python -m pip install meson ninja
    - name: configure
      env:
        CROSS_FILE: |
          [binaries]
          c = 'gcc'
          cpp = 'g++'
          ar = 'gcc-ar'
          strip = 'strip'

          [built-in options]
          c_args = ['-m32']
          c_link_args = ['-m32']
          cpp_args = ['-m32']
          cpp_link_args = ['-m32']

          [host_machine]
          system = 'linux'
          cpu_family = 'x86'
          cpu = 'i686'
          endian = 'little'
      run: |
        echo "$CROSS_FILE" > cross-file.txt
        meson setup --cross-file cross-file.txt /tmp/build \
          -Dwerror=true \
          -Dexamples=true \
          -Dtest=false \
          -Ddoc=false
    - name: build
      run: |
        ninja -C /tmp/build

  build-mac:
    runs-on: macos-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v4
    - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - run: |
          brew install git meson squashfs lz4 xz zstd macfuse
    - run: |
        meson setup /tmp/build \
          -Dwerror=true \
          -Dexamples=true \
          -Dcurl=disabled \
          -Dzlib=enabled \
          -Dlz4=enabled \
          -Dlzma=enabled \
          -Dzstd=enabled \
          -Dfuse-old=enabled \
          -Dfuse=disabled \
          -Dtest=extended \
          -Ddoc=false
    - run: |
          meson test -C /tmp/build -t 5
